version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: jobdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./Backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./Backend
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobdb
      REDIS_ADDR: redis:6379
      PORT: 8080
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Frontend/Homepage
    ports:
      - "80:80"
    depends_on:
      - backend
